// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetAuthenticationLoginParams creates a new GetAuthenticationLoginParams object
//
// There are no default values defined in the spec.
func NewGetAuthenticationLoginParams() GetAuthenticationLoginParams {

	return GetAuthenticationLoginParams{}
}

// GetAuthenticationLoginParams contains all the bound params for the get authentication login operation
// typically these are obtained from a http.Request
//
// swagger:parameters getAuthenticationLogin
type GetAuthenticationLoginParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*redirect url
	  In: query
	*/
	Redirect *string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetAuthenticationLoginParams() beforehand.
func (o *GetAuthenticationLoginParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	qs := runtime.Values(r.URL.Query())

	qRedirect, qhkRedirect, _ := qs.GetOK("redirect")
	if err := o.bindRedirect(qRedirect, qhkRedirect, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindRedirect binds and validates parameter Redirect from query.
func (o *GetAuthenticationLoginParams) bindRedirect(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: false
	// AllowEmptyValue: false

	if raw == "" { // empty values pass all other validations
		return nil
	}
	o.Redirect = &raw

	return nil
}
