// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetWorkflowParams creates a new GetWorkflowParams object
//
// There are no default values defined in the spec.
func NewGetWorkflowParams() GetWorkflowParams {

	return GetWorkflowParams{}
}

// GetWorkflowParams contains all the bound params for the get workflow operation
// typically these are obtained from a http.Request
//
// swagger:parameters getWorkflow
type GetWorkflowParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*workflow name
	  Required: true
	  In: path
	*/
	WorkflowName string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetWorkflowParams() beforehand.
func (o *GetWorkflowParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rWorkflowName, rhkWorkflowName, _ := route.Params.GetOK("workflowName")
	if err := o.bindWorkflowName(rWorkflowName, rhkWorkflowName, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindWorkflowName binds and validates parameter WorkflowName from path.
func (o *GetWorkflowParams) bindWorkflowName(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.WorkflowName = raw

	return nil
}
