// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetAuthenticationLoginHandlerFunc turns a function with the right signature into a get authentication login handler
type GetAuthenticationLoginHandlerFunc func(GetAuthenticationLoginParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAuthenticationLoginHandlerFunc) Handle(params GetAuthenticationLoginParams) middleware.Responder {
	return fn(params)
}

// GetAuthenticationLoginHandler interface for that can handle valid get authentication login params
type GetAuthenticationLoginHandler interface {
	Handle(GetAuthenticationLoginParams) middleware.Responder
}

// NewGetAuthenticationLogin creates a new http.Handler for the get authentication login operation
func NewGetAuthenticationLogin(ctx *middleware.Context, handler GetAuthenticationLoginHandler) *GetAuthenticationLogin {
	return &GetAuthenticationLogin{Context: ctx, Handler: handler}
}

/*
	GetAuthenticationLogin swagger:route GET /auth/login auth getAuthenticationLogin

Authenticate the user
*/
type GetAuthenticationLogin struct {
	Context *middleware.Context
	Handler GetAuthenticationLoginHandler
}

func (o *GetAuthenticationLogin) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetAuthenticationLoginParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
