// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetGithubUserHandlerFunc turns a function with the right signature into a get github user handler
type GetGithubUserHandlerFunc func(GetGithubUserParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetGithubUserHandlerFunc) Handle(params GetGithubUserParams) middleware.Responder {
	return fn(params)
}

// GetGithubUserHandler interface for that can handle valid get github user params
type GetGithubUserHandler interface {
	Handle(GetGithubUserParams) middleware.Responder
}

// NewGetGithubUser creates a new http.Handler for the get github user operation
func NewGetGithubUser(ctx *middleware.Context, handler GetGithubUserHandler) *GetGithubUser {
	return &GetGithubUser{Context: ctx, Handler: handler}
}

/*
	GetGithubUser swagger:route GET /auth/githubuser auth getGithubUser

Get the authenticated user information
*/
type GetGithubUser struct {
	Context *middleware.Context
	Handler GetGithubUserHandler
}

func (o *GetGithubUser) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetGithubUserParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
