// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/goliac-project/goliac/swagger_gen/models"
)

// PostWorkflowForcemergeOKCode is the HTTP code returned for type PostWorkflowForcemergeOK
const PostWorkflowForcemergeOKCode int = 200

/*
PostWorkflowForcemergeOK PR merged

swagger:response postWorkflowForcemergeOK
*/
type PostWorkflowForcemergeOK struct {

	/*
	  In: Body
	*/
	Payload *models.Prmerged `json:"body,omitempty"`
}

// NewPostWorkflowForcemergeOK creates PostWorkflowForcemergeOK with default headers values
func NewPostWorkflowForcemergeOK() *PostWorkflowForcemergeOK {

	return &PostWorkflowForcemergeOK{}
}

// WithPayload adds the payload to the post workflow forcemerge o k response
func (o *PostWorkflowForcemergeOK) WithPayload(payload *models.Prmerged) *PostWorkflowForcemergeOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post workflow forcemerge o k response
func (o *PostWorkflowForcemergeOK) SetPayload(payload *models.Prmerged) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostWorkflowForcemergeOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostWorkflowForcemergeUnauthorizedCode is the HTTP code returned for type PostWorkflowForcemergeUnauthorized
const PostWorkflowForcemergeUnauthorizedCode int = 401

/*
PostWorkflowForcemergeUnauthorized Unauthorized

swagger:response postWorkflowForcemergeUnauthorized
*/
type PostWorkflowForcemergeUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostWorkflowForcemergeUnauthorized creates PostWorkflowForcemergeUnauthorized with default headers values
func NewPostWorkflowForcemergeUnauthorized() *PostWorkflowForcemergeUnauthorized {

	return &PostWorkflowForcemergeUnauthorized{}
}

// WithPayload adds the payload to the post workflow forcemerge unauthorized response
func (o *PostWorkflowForcemergeUnauthorized) WithPayload(payload *models.Error) *PostWorkflowForcemergeUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post workflow forcemerge unauthorized response
func (o *PostWorkflowForcemergeUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostWorkflowForcemergeUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostWorkflowForcemergeForbiddenCode is the HTTP code returned for type PostWorkflowForcemergeForbidden
const PostWorkflowForcemergeForbiddenCode int = 403

/*
PostWorkflowForcemergeForbidden Forbidden

swagger:response postWorkflowForcemergeForbidden
*/
type PostWorkflowForcemergeForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostWorkflowForcemergeForbidden creates PostWorkflowForcemergeForbidden with default headers values
func NewPostWorkflowForcemergeForbidden() *PostWorkflowForcemergeForbidden {

	return &PostWorkflowForcemergeForbidden{}
}

// WithPayload adds the payload to the post workflow forcemerge forbidden response
func (o *PostWorkflowForcemergeForbidden) WithPayload(payload *models.Error) *PostWorkflowForcemergeForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post workflow forcemerge forbidden response
func (o *PostWorkflowForcemergeForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostWorkflowForcemergeForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
PostWorkflowForcemergeDefault generic error response

swagger:response postWorkflowForcemergeDefault
*/
type PostWorkflowForcemergeDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostWorkflowForcemergeDefault creates PostWorkflowForcemergeDefault with default headers values
func NewPostWorkflowForcemergeDefault(code int) *PostWorkflowForcemergeDefault {
	if code <= 0 {
		code = 500
	}

	return &PostWorkflowForcemergeDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post workflow forcemerge default response
func (o *PostWorkflowForcemergeDefault) WithStatusCode(code int) *PostWorkflowForcemergeDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post workflow forcemerge default response
func (o *PostWorkflowForcemergeDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post workflow forcemerge default response
func (o *PostWorkflowForcemergeDefault) WithPayload(payload *models.Error) *PostWorkflowForcemergeDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post workflow forcemerge default response
func (o *PostWorkflowForcemergeDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostWorkflowForcemergeDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
