// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"context"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// PostWorkflowHandlerFunc turns a function with the right signature into a post workflow handler
type PostWorkflowHandlerFunc func(PostWorkflowParams) middleware.Responder

// Handle executing the request and returning a response
func (fn PostWorkflowHandlerFunc) Handle(params PostWorkflowParams) middleware.Responder {
	return fn(params)
}

// PostWorkflowHandler interface for that can handle valid post workflow params
type PostWorkflowHandler interface {
	Handle(PostWorkflowParams) middleware.Responder
}

// NewPostWorkflow creates a new http.Handler for the post workflow operation
func NewPostWorkflow(ctx *middleware.Context, handler PostWorkflowHandler) *PostWorkflow {
	return &PostWorkflow{Context: ctx, Handler: handler}
}

/*
	PostWorkflow swagger:route POST /auth/workflows/{workflowName} auth postWorkflow

Bypass PR approval and force mere the PR
*/
type PostWorkflow struct {
	Context *middleware.Context
	Handler PostWorkflowHandler
}

func (o *PostWorkflow) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostWorkflowParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}

// PostWorkflowBody post workflow body
//
// swagger:model PostWorkflowBody
type PostWorkflowBody struct {

	// explanation
	// Required: true
	// Min Length: 1
	Explanation string `json:"explanation"`

	// pr url
	// Required: true
	// Min Length: 10
	PrURL string `json:"pr_url"`
}

// Validate validates this post workflow body
func (o *PostWorkflowBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateExplanation(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validatePrURL(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *PostWorkflowBody) validateExplanation(formats strfmt.Registry) error {

	if err := validate.RequiredString("body"+"."+"explanation", "body", o.Explanation); err != nil {
		return err
	}

	if err := validate.MinLength("body"+"."+"explanation", "body", o.Explanation, 1); err != nil {
		return err
	}

	return nil
}

func (o *PostWorkflowBody) validatePrURL(formats strfmt.Registry) error {

	if err := validate.RequiredString("body"+"."+"pr_url", "body", o.PrURL); err != nil {
		return err
	}

	if err := validate.MinLength("body"+"."+"pr_url", "body", o.PrURL, 10); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this post workflow body based on context it is used
func (o *PostWorkflowBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (o *PostWorkflowBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *PostWorkflowBody) UnmarshalBinary(b []byte) error {
	var res PostWorkflowBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
