// Code generated by go-swagger; DO NOT EDIT.

package app

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetStatiticsHandlerFunc turns a function with the right signature into a get statitics handler
type GetStatiticsHandlerFunc func(GetStatiticsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetStatiticsHandlerFunc) Handle(params GetStatiticsParams) middleware.Responder {
	return fn(params)
}

// GetStatiticsHandler interface for that can handle valid get statitics params
type GetStatiticsHandler interface {
	Handle(GetStatiticsParams) middleware.Responder
}

// NewGetStatitics creates a new http.Handler for the get statitics operation
func NewGetStatitics(ctx *middleware.Context, handler GetStatiticsHandler) *GetStatitics {
	return &GetStatitics{Context: ctx, Handler: handler}
}

/*
	GetStatitics swagger:route GET /statistics app getStatitics

Get different statistics on Goliac
*/
type GetStatitics struct {
	Context *middleware.Context
	Handler GetStatiticsHandler
}

func (o *GetStatitics) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetStatiticsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
