// Code generated by go-swagger; DO NOT EDIT.

package app

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewGetTeamParams creates a new GetTeamParams object
//
// There are no default values defined in the spec.
func NewGetTeamParams() GetTeamParams {

	return GetTeamParams{}
}

// GetTeamParams contains all the bound params for the get team operation
// typically these are obtained from a http.Request
//
// swagger:parameters getTeam
type GetTeamParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*team name
	  Required: true
	  Min Length: 1
	  In: path
	*/
	TeamID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetTeamParams() beforehand.
func (o *GetTeamParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rTeamID, rhkTeamID, _ := route.Params.GetOK("teamID")
	if err := o.bindTeamID(rTeamID, rhkTeamID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindTeamID binds and validates parameter TeamID from path.
func (o *GetTeamParams) bindTeamID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.TeamID = raw

	if err := o.validateTeamID(formats); err != nil {
		return err
	}

	return nil
}

// validateTeamID carries on validations for parameter TeamID
func (o *GetTeamParams) validateTeamID(formats strfmt.Registry) error {

	if err := validate.MinLength("teamID", "path", o.TeamID, 1); err != nil {
		return err
	}

	return nil
}
