// Code generated by go-swagger; DO NOT EDIT.

package app

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/validate"
)

// NewGetRepositoryParams creates a new GetRepositoryParams object
//
// There are no default values defined in the spec.
func NewGetRepositoryParams() GetRepositoryParams {

	return GetRepositoryParams{}
}

// GetRepositoryParams contains all the bound params for the get repository operation
// typically these are obtained from a http.Request
//
// swagger:parameters getRepository
type GetRepositoryParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*repository slug name
	  Required: true
	  Min Length: 1
	  In: path
	*/
	RepositoryID string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetRepositoryParams() beforehand.
func (o *GetRepositoryParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rRepositoryID, rhkRepositoryID, _ := route.Params.GetOK("repositoryID")
	if err := o.bindRepositoryID(rRepositoryID, rhkRepositoryID, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindRepositoryID binds and validates parameter RepositoryID from path.
func (o *GetRepositoryParams) bindRepositoryID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.RepositoryID = raw

	if err := o.validateRepositoryID(formats); err != nil {
		return err
	}

	return nil
}

// validateRepositoryID carries on validations for parameter RepositoryID
func (o *GetRepositoryParams) validateRepositoryID(formats strfmt.Registry) error {

	if err := validate.MinLength("repositoryID", "path", o.RepositoryID, 1); err != nil {
		return err
	}

	return nil
}
