// Code generated by go-swagger; DO NOT EDIT.

package app

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
)

// NewGetStatiticsParams creates a new GetStatiticsParams object
//
// There are no default values defined in the spec.
func NewGetStatiticsParams() GetStatiticsParams {

	return GetStatiticsParams{}
}

// GetStatiticsParams contains all the bound params for the get statitics operation
// typically these are obtained from a http.Request
//
// swagger:parameters getStatitics
type GetStatiticsParams struct {
	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetStatiticsParams() beforehand.
func (o *GetStatiticsParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
