// Code generated by go-swagger; DO NOT EDIT.

package app

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/goliac-project/goliac/swagger_gen/models"
)

// GetTeamsOKCode is the HTTP code returned for type GetTeamsOK
const GetTeamsOKCode int = 200

/*
GetTeamsOK get list of teams

swagger:response getTeamsOK
*/
type GetTeamsOK struct {

	/*
	  In: Body
	*/
	Payload models.Teams `json:"body,omitempty"`
}

// NewGetTeamsOK creates GetTeamsOK with default headers values
func NewGetTeamsOK() *GetTeamsOK {

	return &GetTeamsOK{}
}

// WithPayload adds the payload to the get teams o k response
func (o *GetTeamsOK) WithPayload(payload models.Teams) *GetTeamsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get teams o k response
func (o *GetTeamsOK) SetPayload(payload models.Teams) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTeamsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.Teams{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*
GetTeamsDefault generic error response

swagger:response getTeamsDefault
*/
type GetTeamsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetTeamsDefault creates GetTeamsDefault with default headers values
func NewGetTeamsDefault(code int) *GetTeamsDefault {
	if code <= 0 {
		code = 500
	}

	return &GetTeamsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get teams default response
func (o *GetTeamsDefault) WithStatusCode(code int) *GetTeamsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get teams default response
func (o *GetTeamsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get teams default response
func (o *GetTeamsDefault) WithPayload(payload *models.Error) *GetTeamsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get teams default response
func (o *GetTeamsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTeamsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
