// Code generated by go-swagger; DO NOT EDIT.

package app

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Alayacare/goliac/swagger_gen/models"
)

// GetStatiticsOKCode is the HTTP code returned for type GetStatiticsOK
const GetStatiticsOKCode int = 200

/*
GetStatiticsOK get Goliac statistics

swagger:response getStatiticsOK
*/
type GetStatiticsOK struct {

	/*
	  In: Body
	*/
	Payload *models.Statistics `json:"body,omitempty"`
}

// NewGetStatiticsOK creates GetStatiticsOK with default headers values
func NewGetStatiticsOK() *GetStatiticsOK {

	return &GetStatiticsOK{}
}

// WithPayload adds the payload to the get statitics o k response
func (o *GetStatiticsOK) WithPayload(payload *models.Statistics) *GetStatiticsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get statitics o k response
func (o *GetStatiticsOK) SetPayload(payload *models.Statistics) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetStatiticsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
GetStatiticsDefault generic error response

swagger:response getStatiticsDefault
*/
type GetStatiticsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetStatiticsDefault creates GetStatiticsDefault with default headers values
func NewGetStatiticsDefault(code int) *GetStatiticsDefault {
	if code <= 0 {
		code = 500
	}

	return &GetStatiticsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get statitics default response
func (o *GetStatiticsDefault) WithStatusCode(code int) *GetStatiticsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get statitics default response
func (o *GetStatiticsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get statitics default response
func (o *GetStatiticsDefault) WithPayload(payload *models.Error) *GetStatiticsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get statitics default response
func (o *GetStatiticsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetStatiticsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
