// Code generated by go-swagger; DO NOT EDIT.

package app

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetCollaboratorHandlerFunc turns a function with the right signature into a get collaborator handler
type GetCollaboratorHandlerFunc func(GetCollaboratorParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCollaboratorHandlerFunc) Handle(params GetCollaboratorParams) middleware.Responder {
	return fn(params)
}

// GetCollaboratorHandler interface for that can handle valid get collaborator params
type GetCollaboratorHandler interface {
	Handle(GetCollaboratorParams) middleware.Responder
}

// NewGetCollaborator creates a new http.Handler for the get collaborator operation
func NewGetCollaborator(ctx *middleware.Context, handler GetCollaboratorHandler) *GetCollaborator {
	return &GetCollaborator{Context: ctx, Handler: handler}
}

/*
	GetCollaborator swagger:route GET /collaborators/{collaboratorID} app getCollaborator

Get collaborator and repos
*/
type GetCollaborator struct {
	Context *middleware.Context
	Handler GetCollaboratorHandler
}

func (o *GetCollaborator) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetCollaboratorParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
