// Code generated by go-swagger; DO NOT EDIT.

package app

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Alayacare/goliac/swagger_gen/models"
)

// GetCollaboratorsOKCode is the HTTP code returned for type GetCollaboratorsOK
const GetCollaboratorsOKCode int = 200

/*
GetCollaboratorsOK get list of collarators

swagger:response getCollaboratorsOK
*/
type GetCollaboratorsOK struct {

	/*
	  In: Body
	*/
	Payload models.Users `json:"body,omitempty"`
}

// NewGetCollaboratorsOK creates GetCollaboratorsOK with default headers values
func NewGetCollaboratorsOK() *GetCollaboratorsOK {

	return &GetCollaboratorsOK{}
}

// WithPayload adds the payload to the get collaborators o k response
func (o *GetCollaboratorsOK) WithPayload(payload models.Users) *GetCollaboratorsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get collaborators o k response
func (o *GetCollaboratorsOK) SetPayload(payload models.Users) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCollaboratorsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = models.Users{}
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}

/*
GetCollaboratorsDefault generic error response

swagger:response getCollaboratorsDefault
*/
type GetCollaboratorsDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetCollaboratorsDefault creates GetCollaboratorsDefault with default headers values
func NewGetCollaboratorsDefault(code int) *GetCollaboratorsDefault {
	if code <= 0 {
		code = 500
	}

	return &GetCollaboratorsDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get collaborators default response
func (o *GetCollaboratorsDefault) WithStatusCode(code int) *GetCollaboratorsDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get collaborators default response
func (o *GetCollaboratorsDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get collaborators default response
func (o *GetCollaboratorsDefault) WithPayload(payload *models.Error) *GetCollaboratorsDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get collaborators default response
func (o *GetCollaboratorsDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetCollaboratorsDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
