// Code generated by go-swagger; DO NOT EDIT.

package app

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetTeamHandlerFunc turns a function with the right signature into a get team handler
type GetTeamHandlerFunc func(GetTeamParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetTeamHandlerFunc) Handle(params GetTeamParams) middleware.Responder {
	return fn(params)
}

// GetTeamHandler interface for that can handle valid get team params
type GetTeamHandler interface {
	Handle(GetTeamParams) middleware.Responder
}

// NewGetTeam creates a new http.Handler for the get team operation
func NewGetTeam(ctx *middleware.Context, handler GetTeamHandler) *GetTeam {
	return &GetTeam{Context: ctx, Handler: handler}
}

/*
	GetTeam swagger:route GET /teams/{teamID} app getTeam

Get team and associated users and repos
*/
type GetTeam struct {
	Context *middleware.Context
	Handler GetTeamHandler
}

func (o *GetTeam) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetTeamParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
