// Code generated by go-swagger; DO NOT EDIT.

package app

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Alayacare/goliac/swagger_gen/models"
)

// PostFlushCacheOKCode is the HTTP code returned for type PostFlushCacheOK
const PostFlushCacheOKCode int = 200

/*
PostFlushCacheOK cache flushed

swagger:response postFlushCacheOK
*/
type PostFlushCacheOK struct {
}

// NewPostFlushCacheOK creates PostFlushCacheOK with default headers values
func NewPostFlushCacheOK() *PostFlushCacheOK {

	return &PostFlushCacheOK{}
}

// WriteResponse to the client
func (o *PostFlushCacheOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*
PostFlushCacheDefault generic error response

swagger:response postFlushCacheDefault
*/
type PostFlushCacheDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostFlushCacheDefault creates PostFlushCacheDefault with default headers values
func NewPostFlushCacheDefault(code int) *PostFlushCacheDefault {
	if code <= 0 {
		code = 500
	}

	return &PostFlushCacheDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post flush cache default response
func (o *PostFlushCacheDefault) WithStatusCode(code int) *PostFlushCacheDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post flush cache default response
func (o *PostFlushCacheDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post flush cache default response
func (o *PostFlushCacheDefault) WithPayload(payload *models.Error) *PostFlushCacheDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post flush cache default response
func (o *PostFlushCacheDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostFlushCacheDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
