// Code generated by go-swagger; DO NOT EDIT.

package app

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/goliac-project/goliac/swagger_gen/models"
)

// PostResyncOKCode is the HTTP code returned for type PostResyncOK
const PostResyncOKCode int = 200

/*
PostResyncOK resync in progress

swagger:response postResyncOK
*/
type PostResyncOK struct {
}

// NewPostResyncOK creates PostResyncOK with default headers values
func NewPostResyncOK() *PostResyncOK {

	return &PostResyncOK{}
}

// WriteResponse to the client
func (o *PostResyncOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*
PostResyncDefault generic error response

swagger:response postResyncDefault
*/
type PostResyncDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostResyncDefault creates PostResyncDefault with default headers values
func NewPostResyncDefault(code int) *PostResyncDefault {
	if code <= 0 {
		code = 500
	}

	return &PostResyncDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post resync default response
func (o *PostResyncDefault) WithStatusCode(code int) *PostResyncDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post resync default response
func (o *PostResyncDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post resync default response
func (o *PostResyncDefault) WithPayload(payload *models.Error) *PostResyncDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post resync default response
func (o *PostResyncDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostResyncDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
