// Code generated by go-swagger; DO NOT EDIT.

package app

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/goliac-project/goliac/swagger_gen/models"
)

// PostExternalCreateRepositoryOKCode is the HTTP code returned for type PostExternalCreateRepositoryOK
const PostExternalCreateRepositoryOKCode int = 200

/*
PostExternalCreateRepositoryOK repository created

swagger:response postExternalCreateRepositoryOK
*/
type PostExternalCreateRepositoryOK struct {
}

// NewPostExternalCreateRepositoryOK creates PostExternalCreateRepositoryOK with default headers values
func NewPostExternalCreateRepositoryOK() *PostExternalCreateRepositoryOK {

	return &PostExternalCreateRepositoryOK{}
}

// WriteResponse to the client
func (o *PostExternalCreateRepositoryOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*
PostExternalCreateRepositoryDefault generic error response

swagger:response postExternalCreateRepositoryDefault
*/
type PostExternalCreateRepositoryDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostExternalCreateRepositoryDefault creates PostExternalCreateRepositoryDefault with default headers values
func NewPostExternalCreateRepositoryDefault(code int) *PostExternalCreateRepositoryDefault {
	if code <= 0 {
		code = 500
	}

	return &PostExternalCreateRepositoryDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post external create repository default response
func (o *PostExternalCreateRepositoryDefault) WithStatusCode(code int) *PostExternalCreateRepositoryDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post external create repository default response
func (o *PostExternalCreateRepositoryDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post external create repository default response
func (o *PostExternalCreateRepositoryDefault) WithPayload(payload *models.Error) *PostExternalCreateRepositoryDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post external create repository default response
func (o *PostExternalCreateRepositoryDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostExternalCreateRepositoryDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
