// Code generated by go-swagger; DO NOT EDIT.

// Package restapi goliac
//
//	goliac is a golang REST application skeleton The base path for all the APIs is "/api/v1".
//
//	Schemes:
//	  http
//	Host: localhost
//	BasePath: /api/v1
//	Version: 1.0.0
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - application/json
//
// swagger:meta
package restapi
