// Code generated by go-swagger; DO NOT EDIT.

package health

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/Alayacare/goliac/internal/swagger_gen/models"
)

// GetLivenessOKCode is the HTTP code returned for type GetLivenessOK
const GetLivenessOKCode int = 200

/*
GetLivenessOK status of health check

swagger:response getLivenessOK
*/
type GetLivenessOK struct {

	/*
	  In: Body
	*/
	Payload *models.Health `json:"body,omitempty"`
}

// NewGetLivenessOK creates GetLivenessOK with default headers values
func NewGetLivenessOK() *GetLivenessOK {

	return &GetLivenessOK{}
}

// WithPayload adds the payload to the get liveness o k response
func (o *GetLivenessOK) WithPayload(payload *models.Health) *GetLivenessOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get liveness o k response
func (o *GetLivenessOK) SetPayload(payload *models.Health) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetLivenessOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
GetLivenessDefault generic error response

swagger:response getLivenessDefault
*/
type GetLivenessDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetLivenessDefault creates GetLivenessDefault with default headers values
func NewGetLivenessDefault(code int) *GetLivenessDefault {
	if code <= 0 {
		code = 500
	}

	return &GetLivenessDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get liveness default response
func (o *GetLivenessDefault) WithStatusCode(code int) *GetLivenessDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get liveness default response
func (o *GetLivenessDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get liveness default response
func (o *GetLivenessDefault) WithPayload(payload *models.Error) *GetLivenessDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get liveness default response
func (o *GetLivenessDefault) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetLivenessDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
