// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Githubuser githubuser
//
// swagger:model githubuser
type Githubuser struct {

	// github id
	GithubID string `json:"github_id,omitempty"`

	// name
	Name string `json:"name,omitempty"`
}

// Validate validates this githubuser
func (m *Githubuser) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this githubuser based on context it is used
func (m *Githubuser) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Githubuser) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Githubuser) UnmarshalBinary(b []byte) error {
	var res Githubuser
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
