// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Prmerged prmerged
//
// swagger:model prmerged
type Prmerged struct {

	// message
	Message string `json:"message,omitempty"`

	// tracking urls
	TrackingUrls []string `json:"tracking_urls"`
}

// Validate validates this prmerged
func (m *Prmerged) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTrackingUrls(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Prmerged) validateTrackingUrls(formats strfmt.Registry) error {
	if swag.IsZero(m.TrackingUrls) { // not required
		return nil
	}

	for i := 0; i < len(m.TrackingUrls); i++ {

		if err := validate.MinLength("tracking_urls"+"."+strconv.Itoa(i), "body", m.TrackingUrls[i], 1); err != nil {
			return err
		}

	}

	return nil
}

// ContextValidate validates this prmerged based on context it is used
func (m *Prmerged) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Prmerged) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Prmerged) UnmarshalBinary(b []byte) error {
	var res Prmerged
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
