// Code generated by go-swagger; DO NOT EDIT.

package models

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// RepositoryDetailsGithubPages repository details github pages
//
// swagger:model repositoryDetailsGithubPages
type RepositoryDetailsGithubPages struct {

	// branch
	Branch string `json:"branch,omitempty"`

	// GitHub Pages custom domain (cname); mirrors spec.github_pages.custom_domain when declared locally.
	CustomDomain string `json:"customDomain,omitempty"`

	// enabled
	Enabled bool `json:"enabled"`

	// Whether HTTPS is enforced for the Pages site (GitHub https_enforced); set with a custom domain in spec.
	EnforceHTTPS bool `json:"enforceHttps,omitempty"`

	// html Url
	HTMLURL string `json:"htmlUrl,omitempty"`

	// path
	Path string `json:"path,omitempty"`

	// source
	Source string `json:"source,omitempty"`

	// visibility
	Visibility string `json:"visibility,omitempty"`
}

// Validate validates this repository details github pages
func (m *RepositoryDetailsGithubPages) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this repository details github pages based on context it is used
func (m *RepositoryDetailsGithubPages) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *RepositoryDetailsGithubPages) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *RepositoryDetailsGithubPages) UnmarshalBinary(b []byte) error {
	var res RepositoryDetailsGithubPages
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
