// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// Statistics statistics
//
// swagger:model statistics
type Statistics struct {

	// last github Api calls
	LastGithubAPICalls int64 `json:"lastGithubApiCalls"`

	// last github throttled
	LastGithubThrottled int64 `json:"lastGithubThrottled"`

	// last time to apply
	LastTimeToApply string `json:"lastTimeToApply"`

	// max github Api calls
	MaxGithubAPICalls int64 `json:"maxGithubApiCalls"`

	// max github throttled
	MaxGithubThrottled int64 `json:"maxGithubThrottled"`

	// max time to apply
	MaxTimeToApply string `json:"maxTimeToApply"`
}

// Validate validates this statistics
func (m *Statistics) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this statistics based on context it is used
func (m *Statistics) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Statistics) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Statistics) UnmarshalBinary(b []byte) error {
	var res Statistics
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
