swagger: '2.0'
info:
  description: >
    goliac is a golang REST application skeleton The base path for all the APIs
    is "/api/v1".
  title: goliac
  version: 1.0.0
tags:
  - name: health
    description: Check if goliac is healthy
x-tagGroups:
  - name: goliac Management
    tags:
      - app
  - name: Health Check
    tags:
      - health
consumes:
  - application/json
produces:
  - application/json
schemes:
  - http
basePath: /api/v1
paths:
  /liveness:
    get:
      tags:
        - health
      operationId: getLiveness
      description: Check if Goliac is healthy
      responses:
        '200':
          description: status of health check
          schema:
            $ref: '#/definitions/health'
        default:
          description: generic error response
          schema:
            $ref: '#/definitions/error'
  /readiness:
    get:
      tags:
        - health
      operationId: getReadiness
      description: Check if Goliac is ready to serve
      responses:
        '200':
          description: status of health check
          schema:
            $ref: '#/definitions/health'
        default:
          description: generic error response
          schema:
            $ref: '#/definitions/error'
  /flushcache:
    post:
      tags:
        - app
      operationId: postFlushCache
      description: Flush the Github remote cache
      responses:
        '200':
          description: cache flushed
        default:
          description: generic error response
          schema:
            $ref: '#/definitions/error'
definitions:
  health:
    type: object
    properties:
      status:
        type: string
  error:
    type: object
    required:
      - message
    properties:
      message:
        type: string
        minLength: 1
